config/routes.rb
Rails.application.routes.draw do
  get 'ainfos/index'

  get 'ainfos/show'

  get 'dinfos/index'

  get 'dinfos/show'

  get 'binfos/index'

  get 'binfos/show'

  get 'avideos/index'

  get 'avideos/show'

  get 'dvideos/index'

  get 'dvideos/show'

  get 'bvideos/index'

  get 'bvideos/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'apblogs/index'

  get 'apblogs/show'

  get 'dpblogs/index'

  get 'dpblogs/show'

  get 'bpblogs/index'

  get 'bpblogs/show'

  get 'project/index'

  get 'project/show'

  get 'shop/index'

  get 'shop/show'

  get 'consult/index'

  get 'consult/show'

  get 'about/index'

  get 'contact/index'

  get 'services/index'
  get 'services/b1'
  get 'services/b2'
  get 'services/b3'
  get 'services/d1'
  get 'services/d2'
  get 'services/d3'
  get 'services/a1'
  get 'services/a2'
  get 'services/a3'
  get 'homes/index'

  mount Commontator::Engine => '/commontator'

  root 'homes#index'

  resources :bpblogs
  resources :dpblogs
  resources :apblogs
  resources :bvideos
  resources :dvideos
  resources :avideos

  resources :bpblogs do
    resources :title, :id, :body, :blopic, :writer
  end
  resources :dpblogs do
    resources :title, :id, :body, :blopic, :writer
  end
  resources :apblogs do
    resources :title, :id, :body, :blopic, :writer
  end
  resources :bvideos do
    resources :tltle, :body
  end
  resources :dvideos do
    resources :tltle, :body
  end
  resources :avideos do
    resources :tltle, :body
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ainfo.rb
class Ainfo < ActiveRecord::Base
	acts_as_commontable
end

app/models/apblog.rb
class Apblog < ActiveRecord::Base
	acts_as_commontable
end

app/models/avideo.rb
class Avideo < ActiveRecord::Base
	acts_as_commontable
end

app/models/binfo.rb
class Binfo < ActiveRecord::Base
	acts_as_commontable
end

app/models/bpblog.rb
class Bpblog < ActiveRecord::Base
	acts_as_commontable
end

app/models/bvideo.rb
class Bvideo < ActiveRecord::Base
	acts_as_commontable
end

app/models/dinfo.rb
class Dinfo < ActiveRecord::Base
	acts_as_commontable
end

app/models/dpblog.rb
class Dpblog < ActiveRecord::Base
	acts_as_commontable
end

app/models/dvideo.rb
class Dvideo < ActiveRecord::Base
	acts_as_commontable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/apblogs_controller.rb
class ApblogsController < ApplicationController
	before_action :authenticate_user!
  def index
    @apblogs = Apblog.all
  end

  def show
    @apblog = Apblog.find(params[:id])
    @apblogs = Apblog.all
    commontator_thread_show(@apblog)
  end

  def create
    Apblog.create(params[:apblog])
  end
  
  def update
    apblog = current_account.apblogs.find(params[:id])
	  apblog.update!(apblog_params)
	  redirect_to apblog
  end
  
private
  def apblog_params
    params.require(:apblog).permit(:title, :body, :id, :writer, :blopic)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/ainfos_helper.rb
module AinfosHelper
end

app/helpers/apblogs_helper.rb
module ApblogsHelper
end

app/helpers/avideos_helper.rb
module AvideosHelper
end

app/helpers/binfos_helper.rb
module BinfosHelper
end

app/helpers/bpblogs_helper.rb
module BpblogsHelper
end

app/helpers/bvideos_helper.rb
module BvideosHelper
end

app/helpers/consult_helper.rb
module ConsultHelper
end

app/helpers/dinfos_helper.rb
module DinfosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/apblogs/index.html.erb
  <!-- Navigation -->
  <div id="navigation">
    <nav class="navbar navbar-custom" role="navigation">
      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <div class="site-logo">
              <a href="#" class="brand">RossGold</a>
            </div>
          </div>


          <div class="col-md-10">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                                                <i class="fa fa-bars"></i>
                                                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="menu">
              <ul class="nav navbar-nav navbar-right">
                <li class="active"><%= link_to 'HOME', '/services/index' %></li>

                <li> <% if current_user %>
                    <%= link_to('LOGOUT', destroy_user_session_path, :method => :delete) %>
                    <% else %></li>
                    <li class="page-scroll">  <%= link_to 'LOGIN', '/users/sign_in' %></li>
                    <li class="page-scroll"> <%= link_to 'SIGNUP', '/users/sign_up' %></li>
                    <% end %> 
              </ul>
            </div>
            <!-- /.Navbar-collapse -->

          </div>
        </div>
      </div>
      <!-- /.container -->
    </nav>
  </div>
  <!-- /Navigation -->
<br>
    <div class="container">
     <h1 class="text-left"><strong> Welcome <% if current_user %><%= current_user.user_name %><% end %> </strong> </h1>
    <br>
    <h1 class="text-center"></h1>
    <div class="row" id="features">
    	<% for apblog in @apblogs %>
				<div class="col-sm-4 feature">
						<%= raw(apblog.blopic) %>
						<h2 class="text-center"><%= link_to apblog.title, apblog_path(apblog) %></h2>
                        <h6 class="text-muted text-right"><%= apblog.writer %></h6>						
				</div><!-- end feature -->
		<% end %>
    </div>
    
            </div>
    


    <!-- Section: contact -->
  <section id="contact" class="home-section nopadd-bot color-dark bg-white text-center">
    <div class="container marginbot-50">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="animatedParent">
            <div class="section-heading text-center">
              <h2 class="h-bold animated bounceInDown">Contact us</h2>
              <div class="divider-header"></div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="container text-center">
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
            <p>+233 (0)50 123 4567 </p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
            <p>info@rossgold.com</p>
            <br>
            <p>
              <a href="mailto:info@lesra.com"><button type="submit" class="btn btn-primary btn-lg btn-block" style="color: black;">Send Message</button></a>
            </p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-clock-o fa-3x mb-3 sr-contact"></i>
            <p>Monday - Friday: 7am - 5pm</p>
          </div>
        </div>
    </div>
  </section>
  <br>
   <section>

    <div class="container text-center">
      <div class="row">
        <div class="col-md-6 text-center">
          <h2 class="section-title"></h2>
        </div>
      </div>
    </div>
  </section>
  <!-- /Section: contact -->
  <br>
  <br>
  <!-- google map -->
  <div class="text-center">
  <p id="map-btn2" class="text-center btn btn-blood btn-lg btn-noradius gmap-btn close-map-button btn-hide" data-placement="top" style="color: black;">
    Teshie Nungua Estate, Accra-Ghana 
    <div style="display: horizontal">
              <ul>
                <a href="#" ><i class="fa fa-facebook"></i></a> |
                
                <a href="#" ><i class="fa fa-twitter"></i></a> |
                
                <a href="#" ><i class="fa fa-instagram"></i></a>
              </ul>
            </div>
    </p>
  </div>
  <!-- google map -->
  <section id="map" class="close-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7941.34795919646!2d-0.046913042339332155!3d5.615068867180036!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf86ef08de8895%3A0xe6ffb8fe0118ff81!2zNcKwMzcnMDEuNyJOIDDCsDAyJzUzLjgiVw!5e0!3m2!1sen!2sgh!4v1527384450558" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
  </section>
  <!-- /google map -->

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center copyright" style="font-size: 1.1em;">
          &copy; 2017 - 2018 Copyright RossGold. All Rights Reserved
          
          <div class="credits" style="color: white;">
            <a href="#">Website Made by David Adafia | +233 (0)24 2911 291 | davidadfia@gmail.com</a>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/apblogs/show.html.erb
    <br>
    <br>
    <br>
    <br>
    <br>
    	<div class="container">
    		<p><%= raw(@apblog.body) %></p>
    		<br>
        	
        	<br>
            <%= commontator_thread(@apblog) %>
        </div>
    <br>
<div class="text-center">
<%= link_to "Back", :back, :class => "btn btn-default btn-lg" %>
</div>
<br>